name: test-action
on:
    workflow_dispatch:

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "Hello World!"
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy
              run: echo "Deploy Please"
            - name: build
              run: echo "build please"